(function(){
'use strict';
const dialog=document.getElementById('toolDialog'),title=document.getElementById('toolTitle'),subtitle=document.getElementById('toolSubtitle'),body=document.getElementById('toolBody');
let current='',timer={end:0,remain:300000,running:false,tick:null},watch={start:0,elapsed:0,running:false,tick:null},pomo={mode:'work',end:0,remain:1500000,running:false,tick:null},calendarDate=new Date(),overlay=null,alarmTick=null;
const meta={
timer:['Timer','Đếm ngược và báo âm thanh'],stopwatch:['Stopwatch','Bấm giờ chính xác'],pomodoro:['Pomodoro','Chu kỳ tập trung 25 phút / nghỉ 5 phút'],alarm:['Báo thức','Hẹn một thời điểm trong ngày'],
calculator:['Máy tính','Tính toán bằng remote'],convert:['Đổi đơn vị','Độ dài, khối lượng, nhiệt độ, dung lượng'],calendar:['Lịch','Xem lịch tháng'],notes:['Ghi chú','Lưu cục bộ trên TV'],
bigtext:['Bảng chữ lớn','Hiển thị thông báo toàn màn hình'],random:['Random','Sinh số ngẫu nhiên'],password:['Tạo mật khẩu','Tạo hoàn toàn offline'],video:['Video Local','Phát file từ USB hoặc bộ nhớ TV'],
music:['Nhạc Local','Phát file âm thanh từ TV/USB'],iptv:['IPTV Player','Stream phát ngay trong TV Hub'],network:['Test mạng','Đo trạng thái và phản hồi'],device:['Thông tin TV','Màn hình, CPU, RAM và browser'],
screen:['Test màn hình','Màu đơn, gradient, checkerboard'],overscan:['Căn Overscan','Kiểm tra mép hình có bị cắt'],speaker:['Test loa','Kiểm tra trái, phải, cả hai'],remote:['Test remote','Xem phím mà browser nhận được']
};
function openTool(name,from){current=name;const m=meta[name];title.textContent=m[0];subtitle.textContent=m[1];render(name);openDialog(dialog,from)}
function render(n){const fn={timer:renderTimer,stopwatch:renderStopwatch,pomodoro:renderPomodoro,alarm:renderAlarm,calculator:renderCalculator,convert:renderConvert,calendar:renderCalendar,notes:renderNotes,bigtext:renderBigText,random:renderRandom,password:renderPassword,video:renderVideo,music:renderMusic,iptv:renderIPTV,network:renderNetwork,device:renderDevice,screen:renderScreen,overscan:renderOverscan,speaker:renderSpeaker,remote:renderRemote}[n];if(fn)fn()}
function fmt(ms,centi){ms=Math.max(0,ms);const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000),c=Math.floor(ms%1000/10);const base=(h?String(h).padStart(2,'0')+':':'')+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');return centi?base+'.'+String(c).padStart(2,'0'):base}
function beep(freq=660,pan=0,dur=.8){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)throw 0;const ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.18,ctx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+dur);if(ctx.createStereoPanner){const p=ctx.createStereoPanner();p.pan.value=pan;o.connect(g);g.connect(p);p.connect(ctx.destination)}else{o.connect(g);g.connect(ctx.destination)}o.start();o.stop(ctx.currentTime+dur+.03);setTimeout(()=>ctx.close().catch(()=>{}),(dur+.3)*1000)}catch{showToast('Browser không hỗ trợ Web Audio')}}
function renderTimer(){
 body.innerHTML='<div class="tool-panel"><div id="timerOut" class="tool-display">'+fmt(timer.running?timer.end-Date.now():timer.remain)+'</div><div class="tool-row"><input id="timerMin" class="focusable" type="number" min=".1" step=".5" value="'+(timer.remain/60000).toFixed(1)+'"><button id="timerSet" class="btn focusable">Đặt phút</button></div><div class="tool-row"><button id="timerGo" class="btn primary focusable">'+(timer.running?'Tạm dừng':'Bắt đầu')+'</button><button class="btn focusable preset" data-v="60000">1 phút</button><button class="btn focusable preset" data-v="300000">5 phút</button><button class="btn focusable preset" data-v="900000">15 phút</button></div></div>';
 const out=document.getElementById('timerOut'),paint=()=>{if(out&&document.body.contains(out))out.textContent=fmt(timer.running?timer.end-Date.now():timer.remain)};
 clearInterval(timer.tick);timer.tick=setInterval(()=>{if(timer.running&&timer.end<=Date.now()){timer.running=false;timer.remain=0;beep(880,0,1.2);showToast('Timer đã hết giờ')}paint()},250);
 document.getElementById('timerSet').onclick=()=>{const v=parseFloat(document.getElementById('timerMin').value);if(!(v>0))return showToast('Số phút không hợp lệ');timer.running=false;timer.remain=v*60000;paint()};
 document.getElementById('timerGo').onclick=function(){if(timer.running){timer.remain=Math.max(0,timer.end-Date.now());timer.running=false;this.textContent='Bắt đầu'}else{if(timer.remain<=0)timer.remain=300000;timer.end=Date.now()+timer.remain;timer.running=true;this.textContent='Tạm dừng'}paint()};
 body.querySelectorAll('.preset').forEach(b=>b.onclick=()=>{timer.running=false;timer.remain=Number(b.dataset.v);document.getElementById('timerMin').value=(timer.remain/60000).toFixed(1);document.getElementById('timerGo').textContent='Bắt đầu';paint()});
}
function renderStopwatch(){body.innerHTML='<div class="tool-panel"><div id="watchOut" class="tool-display">'+fmt(watch.elapsed,true)+'</div><div class="tool-row"><button id="watchGo" class="btn primary focusable">'+(watch.running?'Tạm dừng':'Bắt đầu')+'</button><button id="watchReset" class="btn focusable">Đặt lại</button></div></div>';const out=document.getElementById('watchOut'),paint=()=>{if(out&&document.body.contains(out))out.textContent=fmt(watch.elapsed+(watch.running?Date.now()-watch.start:0),true)};clearInterval(watch.tick);watch.tick=setInterval(paint,31);document.getElementById('watchGo').onclick=function(){if(watch.running){watch.elapsed+=Date.now()-watch.start;watch.running=false;this.textContent='Bắt đầu'}else{watch.start=Date.now();watch.running=true;this.textContent='Tạm dừng'}paint()};document.getElementById('watchReset').onclick=()=>{watch.running=false;watch.elapsed=0;document.getElementById('watchGo').textContent='Bắt đầu';paint()}}
function renderPomodoro(){
 body.innerHTML='<div class="tool-panel"><div id="pomoMode" class="tool-status"></div><div id="pomoOut" class="tool-display"></div><div class="tool-row"><button id="pomoGo" class="btn primary focusable">'+(pomo.running?'Tạm dừng':'Bắt đầu')+'</button><button id="pomoSwitch" class="btn focusable">Đổi Work / Break</button><button id="pomoReset" class="btn focusable">Đặt lại</button></div></div>';
 const out=$id('pomoOut'),mode=$id('pomoMode'),paint=()=>{mode.textContent=pomo.mode==='work'?'TẬP TRUNG · 25 phút':'NGHỈ · 5 phút';out.textContent=fmt(pomo.running?pomo.end-Date.now():pomo.remain)};
 clearInterval(pomo.tick);pomo.tick=setInterval(()=>{if(pomo.running&&pomo.end<=Date.now()){pomo.running=false;pomo.mode=pomo.mode==='work'?'break':'work';pomo.remain=pomo.mode==='work'?1500000:300000;beep(pomo.mode==='work'?880:660,0,1);showToast('Pomodoro chuyển sang '+(pomo.mode==='work'?'Tập trung':'Nghỉ'))}paint()},250);
 $id('pomoGo').onclick=function(){if(pomo.running){pomo.remain=Math.max(0,pomo.end-Date.now());pomo.running=false;this.textContent='Bắt đầu'}else{pomo.end=Date.now()+pomo.remain;pomo.running=true;this.textContent='Tạm dừng'}paint()};
 $id('pomoSwitch').onclick=()=>{pomo.running=false;pomo.mode=pomo.mode==='work'?'break':'work';pomo.remain=pomo.mode==='work'?1500000:300000;$id('pomoGo').textContent='Bắt đầu';paint()};
 $id('pomoReset').onclick=()=>{pomo.running=false;pomo.remain=pomo.mode==='work'?1500000:300000;$id('pomoGo').textContent='Bắt đầu';paint()};paint();
}
function $id(x){return document.getElementById(x)}
function renderAlarm(){
 const saved=localStorage.getItem('tvAlarmV4')||'';
 body.innerHTML='<div class="tool-panel"><div class="tool-display">⏰</div><div class="tool-row"><input id="alarmTime" class="focusable" type="time" value="'+escapeHtml(saved)+'"><button id="alarmSave" class="btn primary focusable">Bật báo thức</button><button id="alarmOff" class="btn focusable">Tắt</button></div><div id="alarmStatus" class="tool-status"></div></div>';
 const status=$id('alarmStatus'),paint=()=>{const v=localStorage.getItem('tvAlarmV4');status.textContent=v?'Đang bật báo thức lúc '+v+' mỗi ngày. TV Hub phải đang mở.':'Báo thức đang tắt.'};paint();
 $id('alarmSave').onclick=()=>{const v=$id('alarmTime').value;if(!v)return showToast('Chọn giờ báo thức');localStorage.setItem('tvAlarmV4',v);localStorage.removeItem('tvAlarmLastV4');paint();showToast('Đã bật báo thức')};
 $id('alarmOff').onclick=()=>{localStorage.removeItem('tvAlarmV4');paint()};
}
function checkAlarm(){const a=localStorage.getItem('tvAlarmV4');if(!a)return;const n=new Date(),now=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0'),day=n.toISOString().slice(0,10),last=localStorage.getItem('tvAlarmLastV4');if(now===a&&last!==day){localStorage.setItem('tvAlarmLastV4',day);beep(880,0,2);showToast('⏰ Báo thức '+a)}}
alarmTick=setInterval(checkAlarm,1000);
function calcValue(text){const s=String(text||'').replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-').replace(/\s+/g,'');let i=0;function num(){const st=i;while(i<s.length&&/[0-9.]/.test(s[i]))i++;if(st===i)throw 0;const v=Number(s.slice(st,i));if(!isFinite(v))throw 0;return v}function fac(){if(s[i]==='-'){i++;return-fac()}if(s[i]==='+'){i++;return fac()}if(s[i]==='('){i++;const v=expr();if(s[i]!==')')throw 0;i++;return v}return num()}function term(){let v=fac();while(i<s.length&&'*/%'.includes(s[i])){const o=s[i++],r=fac();v=o==='*'?v*r:o==='/'?v/r:v%r}return v}function expr(){let v=term();while(i<s.length&&(s[i]==='+'||s[i]==='-')){const o=s[i++],r=term();v=o==='+'?v+r:v-r}return v}const v=expr();if(i!==s.length||!isFinite(v))throw 0;return v}
function renderCalculator(){const keys=['C','(',')','÷','7','8','9','×','4','5','6','−','1','2','3','+','0','.','%','='];body.innerHTML='<div class="tool-panel"><div id="calcOut" class="tool-display calc-display">0</div><div id="calcGrid" class="calc-grid">'+keys.map(k=>'<button class="btn focusable" data-k="'+k+'">'+k+'</button>').join('')+'</div></div>';let exp='';$id('calcGrid').onclick=e=>{const b=e.target.closest('button');if(!b)return;const k=b.dataset.k;if(k==='C'){exp='';$id('calcOut').textContent='0'}else if(k==='='){try{exp=String(Math.round((calcValue(exp)+Number.EPSILON)*1e8)/1e8);$id('calcOut').textContent=exp}catch{$id('calcOut').textContent='Lỗi';exp=''}}else{exp+=k;$id('calcOut').textContent=exp}}}
function renderConvert(){
 body.innerHTML='<div class="tool-panel"><div class="tool-row"><select id="convType" class="focusable"><option value="length">Độ dài</option><option value="weight">Khối lượng</option><option value="temp">Nhiệt độ</option><option value="storage">Dung lượng</option></select><input id="convValue" class="focusable" type="number" value="1"><select id="convFrom" class="focusable"></select><span>→</span><select id="convTo" class="focusable"></select><button id="convGo" class="btn primary focusable">Đổi</button></div><div id="convOut" class="tool-display">—</div></div>';
 const defs={length:{m:1,km:1000,cm:.01,mm:.001,ft:.3048,in:.0254},weight:{kg:1,g:.001,lb:.45359237,oz:.028349523125},storage:{B:1,KB:1024,MB:1048576,GB:1073741824,TB:1099511627776}};
 function fill(){const t=$id('convType').value,units=t==='temp'?['°C','°F','K']:Object.keys(defs[t]);$id('convFrom').innerHTML=units.map(x=>'<option>'+x+'</option>').join('');$id('convTo').innerHTML=units.map(x=>'<option>'+x+'</option>').join('');$id('convTo').selectedIndex=1}
 function go(){const t=$id('convType').value,v=Number($id('convValue').value),f=$id('convFrom').value,to=$id('convTo').value;if(!isFinite(v))return;if(t==='temp'){let c=f==='°C'?v:f==='°F'?(v-32)*5/9:v-273.15;let r=to==='°C'?c:to==='°F'?c*9/5+32:c+273.15;$id('convOut').textContent=r.toFixed(4).replace(/\.0+$/,'')+' '+to}else{const r=v*defs[t][f]/defs[t][to];$id('convOut').textContent=Number(r.toPrecision(10))+' '+to}}
 $id('convType').onchange=fill;$id('convGo').onclick=go;fill();go();
}
function renderCalendar(){body.innerHTML='<div class="tool-panel"><div class="calendar-head"><button id="calPrev" class="btn focusable">← Tháng trước</button><div id="calTitle" class="calendar-title"></div><button id="calNext" class="btn focusable">Tháng sau →</button></div><div id="calGrid" class="calendar-grid"></div></div>';function paint(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),off=(first.getDay()+6)%7,now=new Date();$id('calTitle').textContent='Tháng '+(m+1)+' / '+y;let html=['T2','T3','T4','T5','T6','T7','CN'].map(x=>'<div class="dow">'+x+'</div>').join('');for(let i=0;i<off;i++)html+='<div class="empty"></div>';for(let d=1;d<=days;d++)html+='<div class="'+(d===now.getDate()&&m===now.getMonth()&&y===now.getFullYear()?'today-cell':'')+'">'+d+'</div>';$id('calGrid').innerHTML=html}$id('calPrev').onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);paint()};$id('calNext').onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);paint()};paint()}
function renderNotes(){const saved=localStorage.getItem('tvNotesV4')||'';body.innerHTML='<div class="tool-panel"><textarea id="notesArea" class="tool-textarea focusable" placeholder="Nhập ghi chú...">'+escapeHtml(saved)+'</textarea><div class="tool-row"><button id="notesSave" class="btn primary focusable">Lưu</button><button id="notesClear" class="btn danger focusable">Xóa</button></div></div>';$id('notesSave').onclick=()=>{localStorage.setItem('tvNotesV4',$id('notesArea').value);showToast('Đã lưu')};$id('notesClear').onclick=()=>{$id('notesArea').value='';localStorage.removeItem('tvNotesV4')}}
function renderBigText(){body.innerHTML='<div class="tool-panel"><textarea id="bigTextInput" class="tool-textarea focusable" placeholder="Nhập chữ muốn hiển thị thật lớn..."></textarea><div class="tool-row"><button id="bigTextShow" class="btn primary focusable">Hiển thị toàn màn hình</button></div></div>';$id('bigTextShow').onclick=()=>{const txt=$id('bigTextInput').value.trim();if(!txt)return showToast('Nhập nội dung');showOverlay('bigtext',txt)}}
function renderRandom(){body.innerHTML='<div class="tool-panel"><div class="tool-row"><input id="randMin" class="focusable" type="number" value="1"><span>đến</span><input id="randMax" class="focusable" type="number" value="100"><button id="randGo" class="btn primary focusable">Random</button></div><div id="randOut" class="tool-display">?</div></div>';$id('randGo').onclick=()=>{let a=Math.ceil(Number($id('randMin').value)),b=Math.floor(Number($id('randMax').value));if(!isFinite(a)||!isFinite(b)||a>b)return showToast('Khoảng số không hợp lệ');$id('randOut').textContent=String(Math.floor(Math.random()*(b-a+1))+a)}}
function renderPassword(){body.innerHTML='<div class="tool-panel"><div class="tool-row"><input id="passLen" class="focusable" type="number" min="4" max="128" value="20"><button id="passGo" class="btn primary focusable">Tạo mật khẩu</button><button id="passCopy" class="btn focusable">Sao chép</button></div><div id="passOut" class="tool-display" style="font-size:30px;word-break:break-all">—</div></div>';const make=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*_-+=';let n=Math.min(128,Math.max(4,Number($id('passLen').value)||20)),s='';const arr=new Uint32Array(n);crypto.getRandomValues(arr);for(let i=0;i<n;i++)s+=chars[arr[i]%chars.length];$id('passOut').textContent=s};$id('passGo').onclick=make;$id('passCopy').onclick=async()=>{const s=$id('passOut').textContent;if(s==='—')return;try{await navigator.clipboard.writeText(s);showToast('Đã sao chép')}catch{showToast('Browser không cho phép clipboard')}};make()}
function renderVideo(){body.innerHTML='<div class="tool-panel"><video id="videoPlayer" class="media-player" controls playsinline></video><div class="tool-row"><input id="videoFile" class="focusable" type="file" accept="video/*"><button id="videoToggle" class="btn primary focusable">Play / Pause</button></div><div class="tool-status">Chỉ phát file bạn chọn từ TV/USB. Không mở trang ngoài.</div></div>';const p=$id('videoPlayer');$id('videoFile').onchange=function(){const f=this.files&&this.files[0];if(!f)return;p.src=URL.createObjectURL(f);p.play().catch(()=>{})};$id('videoToggle').onclick=()=>p.paused?p.play().catch(()=>{}):p.pause()}
function renderMusic(){body.innerHTML='<div class="tool-panel"><div class="tool-display" style="font-size:54px">🎵</div><audio id="audioPlayer" class="audio-player" controls></audio><div class="tool-row"><input id="audioFile" class="focusable" type="file" accept="audio/*"><button id="audioToggle" class="btn primary focusable">Play / Pause</button></div></div>';const p=$id('audioPlayer');$id('audioFile').onchange=function(){const f=this.files&&this.files[0];if(!f)return;p.src=URL.createObjectURL(f);p.play().catch(()=>{})};$id('audioToggle').onclick=()=>p.paused?p.play().catch(()=>{}):p.pause()}
function parseM3U(text){const lines=String(text||'').split(/\r?\n/),out=[];let name='';lines.forEach(line=>{line=line.trim();if(!line)return;if(line.startsWith('#EXTINF:')){const i=line.lastIndexOf(',');name=i>=0?line.slice(i+1).trim():'Kênh'}else if(line[0]!=='#'){out.push({name:name||('Kênh '+(out.length+1)),url:line});name=''}});return out.slice(0,300)}
function renderIPTV(){body.innerHTML='<div class="tool-panel"><video id="iptvPlayer" class="media-player" controls playsinline></video><div class="tool-row"><input id="iptvUrl" class="focusable" type="url" placeholder="URL stream .m3u8 / MP4"><button id="iptvPlay" class="btn primary focusable">Phát trong Hub</button></div><textarea id="m3uText" class="tool-textarea focusable" style="min-height:140px" placeholder="Dán playlist M3U hoặc chọn file M3U..."></textarea><div class="tool-row"><input id="m3uFile" class="focusable" type="file" accept=".m3u,.m3u8,text/plain"><button id="m3uParse" class="btn focusable">Đọc M3U</button></div><div id="channelList" class="channel-list"></div><div class="tool-status">Stream được phát trong chính TV Hub; không chuyển sang website khác.</div></div>';const p=$id('iptvPlayer'),play=u=>{if(!u)return showToast('URL stream trống');p.src=u;p.play().catch(()=>showToast('Browser không phát được stream này'))},draw=t=>{const ch=parseM3U(t);$id('channelList').innerHTML=ch.map((x,i)=>'<button class="btn channel-btn focusable" data-i="'+i+'">'+escapeHtml(x.name)+'</button>').join('');$id('channelList').querySelectorAll('button').forEach(b=>b.onclick=()=>play(ch[Number(b.dataset.i)].url));showToast('Đã đọc '+ch.length+' kênh')};$id('iptvPlay').onclick=()=>play($id('iptvUrl').value.trim());$id('m3uParse').onclick=()=>draw($id('m3uText').value);$id('m3uFile').onchange=function(){const f=this.files&&this.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{$id('m3uText').value=String(r.result||'');draw(r.result)};r.readAsText(f)}}
function metric(k,v){return '<div class="metric"><small>'+escapeHtml(k)+'</small><b>'+escapeHtml(v)+'</b></div>'}
function renderNetwork(){const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection||{};body.innerHTML='<div class="tool-panel"><div class="network-metrics">'+metric('Internet',navigator.onLine?'Online':'Offline')+metric('Loại mạng',c.effectiveType?String(c.effectiveType).toUpperCase():'N/A')+metric('Downlink API',typeof c.downlink==='number'?c.downlink+' Mbps':'N/A')+metric('RTT API',typeof c.rtt==='number'?c.rtt+' ms':'N/A')+'</div><div id="netResult" class="tool-status">Nhấn Chạy test để đo phản hồi tới chính file của TV Hub.</div><button id="netRun" class="btn primary focusable">Chạy test</button></div>';$id('netRun').onclick=async()=>{const o=$id('netResult');o.textContent='Đang đo...';try{const samples=[];for(let i=0;i<3;i++){const t=performance.now(),r=await fetch('./app.js?probe='+Date.now()+'-'+i,{cache:'no-store'});await r.text();samples.push(performance.now()-t)}o.textContent='Phản hồi trung bình: '+(samples.reduce((a,b)=>a+b,0)/samples.length).toFixed(0)+' ms · 3 lượt'}catch{o.textContent='Không đo được kết nối'}}}
function renderDevice(){const c=navigator.connection||{};const rows=[['Nền tảng',navigator.platform||'N/A'],['Màn hình',screen.width+' × '+screen.height],['Viewport',innerWidth+' × '+innerHeight],['Pixel ratio',String(devicePixelRatio||1)],['CPU logic',navigator.hardwareConcurrency?String(navigator.hardwareConcurrency):'N/A'],['RAM ước tính',navigator.deviceMemory?navigator.deviceMemory+' GB':'N/A'],['Kết nối',c.effectiveType?String(c.effectiveType).toUpperCase():'N/A'],['Ngôn ngữ',navigator.language||'N/A'],['Phiên bản','V4.0.0'],['Browser',navigator.userAgent||'N/A']];body.innerHTML='<div class="device-grid">'+rows.map(x=>metric(x[0],x[1])).join('')+'</div>'}
function renderScreen(){const opts=[['Đỏ','#f00'],['Xanh lá','#0f0'],['Xanh dương','#00f'],['Trắng','#fff'],['Đen','#000'],['Xám','#808080'],['Gradient','gradient'],['Checkerboard','checker']];body.innerHTML='<div class="tool-panel"><div class="screen-options">'+opts.map(o=>'<button class="btn focusable screenChoice" data-p="'+o[1]+'">'+o[0]+'</button>').join('')+'</div><div class="tool-status">Nhấn phím bất kỳ để thoát test.</div></div>';body.querySelectorAll('.screenChoice').forEach(b=>b.onclick=()=>showOverlay(b.dataset.p,''))}
function renderOverscan(){body.innerHTML='<div class="tool-panel"><div class="tool-status">Mở khung căn chỉnh. Nếu bạn không nhìn đủ bốn cạnh trắng thì TV/browser đang cắt mép.</div><button id="overShow" class="btn primary focusable">Mở khung Overscan</button></div>';$id('overShow').onclick=()=>showOverlay('overscan','')}
function renderSpeaker(){body.innerHTML='<div class="tool-panel"><div class="tool-display" style="font-size:58px">🔊</div><div class="tool-row"><button id="left" class="btn focusable">◀ Trái</button><button id="both" class="btn primary focusable">Cả hai</button><button id="right" class="btn focusable">Phải ▶</button></div></div>';$id('left').onclick=()=>beep(440,-1,.8);$id('both').onclick=()=>beep(440,0,.8);$id('right').onclick=()=>beep(440,1,.8)}
function renderRemote(){body.innerHTML='<div class="tool-panel"><div class="remote-display"><div id="remoteKey" class="remote-key">Nhấn phím</div><div id="remoteCode" class="remote-code">↑ ↓ ← → OK Back...</div></div><div class="tool-status">Một số phím hệ thống như Home/Power có thể bị Android giữ lại.</div></div>'}
function showOverlay(type,text){closeOverlay();overlay=document.createElement('div');if(type==='bigtext'){overlay.className='bigtext-overlay';overlay.textContent=text}else{overlay.className='screen-overlay';if(type==='gradient')overlay.style.background='linear-gradient(90deg,#000,#fff,#000)';else if(type==='checker')overlay.style.background='repeating-conic-gradient(#fff 0 25%,#000 0 50%) 50% / 80px 80px';else if(type==='overscan'){overlay.style.background='#111';overlay.innerHTML='<div class="overscan-box"></div><div class="screen-hint">Phải nhìn đủ 4 cạnh trắng · Nhấn phím để thoát</div>'}else overlay.style.background=type;if(type!=='overscan')overlay.innerHTML='<div class="screen-hint">Nhấn phím bất kỳ để thoát</div>'}document.body.appendChild(overlay);overlay.onpointerdown=closeOverlay}
function closeOverlay(){if(overlay){overlay.remove();overlay=null;return true}return false}
document.querySelectorAll('[data-direct-tool]').forEach(b=>b.addEventListener('click',()=>openTool(b.dataset.directTool,b)));
document.addEventListener('keydown',e=>{if(overlay){e.preventDefault();e.stopImmediatePropagation();closeOverlay();return}if(current==='remote'&&dialog.open){const k=$id('remoteKey'),c=$id('remoteCode');if(k)k.textContent=e.key||'(không có key)';if(c)c.textContent='keyCode: '+e.keyCode+' · code: '+(e.code||'N/A')+' · repeat: '+(e.repeat?'YES':'NO')}},true);
dialog.addEventListener('close',()=>{current='';closeOverlay()});
})();